# SPDX-FileCopyrightText: 2023-2025 Dom Rodriguez (shymega) <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: "Container Image builder workflow"

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-container-image:
    name: Build and push container image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Build image with Nix
        run: podman load -i $(nix build --print-out-paths .#oci)
      - name: Push container to GHCR
        uses: redhat-actions/push-to-registry@v2.8
        with:
          image: ghcr.io/verma-project/verma_server
          tags: latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
